name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.3.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: ">=1.0.0 <3.0.0"

dependencies:
  collection: ">=1.4.1 <2.0.0"
  http: ^0.13.3
  http_parser: ">=3.0.0 <5.0.0"
  logging: ^1.0.2
  sync: ">=0.1.0 <0.3.0"

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
