name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.3.0
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.4
  http_parser: ^4.0.1
  logging: ^1.0.2
  sync: ^0.3.0

dev_dependencies:
  test: ^1.21.4
